### ISSUE TITLE
Can not delete a model with a ManyToManyField

### ISSUE THREAD

**Issue by kuno** [lsbardel/python-stdnet#21]
## In [35]: a.delete()

AttributeError                            Traceback (most recent call last)
/home/kuno/utopia/sogoke-django/sogoke/<ipython-input-35-7bdca98f20ae> in <module>()
----> 1 a.delete()

/home/kuno/utopia/sogoke-django/lib/python2.7/site-packages/stdnet/orm/models.pyc in delete(self, transaction)
    165         for obj in self.related_objects():
    166             T += obj.delete(transaction)
--> 167         res = T + meta.cursor.delete_object(self, transaction)
    168         post_delete.send(sender=self.**class**, instance = self)
    169         return res

/home/kuno/utopia/sogoke-django/lib/python2.7/site-packages/stdnet/backends/base.pyc in delete_object(self, obj, transaction)
    167 
    168         self._remove_indexes(obj, transaction)
--> 169         self._delete_object(obj, transaction)
    170 
    171         if commit:

/home/kuno/utopia/sogoke-django/lib/python2.7/site-packages/stdnet/backends/redisb.pyc in _delete_object(self, obj, transaction)
    413         if mfs:
    414             pipe = transaction.pipe
--> 415             fids = [fid for fid in (field.id(obj) for field in mfs) if fid]
    416             if fids:
    417                 pipe.delete(*fids)

/home/kuno/utopia/sogoke-django/lib/python2.7/site-packages/stdnet/backends/redisb.pyc in <genexpr>((field,))
    413         if mfs:
    414             pipe = transaction.pipe
--> 415             fids = [fid for fid in (field.id(obj) for field in mfs) if fid]
    416             if fids:
    417                 pipe.delete(*fids)

/home/kuno/utopia/sogoke-django/lib/python2.7/site-packages/stdnet/orm/std.pyc in id(self, obj)
    138 
    139     def id(self, obj):
--> 140         return getattr(obj,self.attname).id
    141 
    142 

AttributeError: 'M2MRelatedManager' object has no attribute 'id'

**Comment by lsbardel** [comment]
Looks like a serious bug and there are no tests for it!

**Comment by lsbardel** [comment]
This has been fixed on branch 0.6 and 0.7. I will release `0.6.2` to pypi this evening.
Thanks for stack trace.

**Comment by kuno** [comment]
thanks! It works now ; )
