### ISSUE TITLE
re-index?

### ISSUE THREAD

**Issue by kuno** [lsbardel/python-stdnet#25]
Is it possible to make a non-index field became index after the model has already been registered and stored some data?

**Comment by lsbardel** [comment]
Yes you can, but you need to re-save all the instances.

```
for obj in Yourmodel.objects.all():
    obj.save()
```

**Comment by kuno** [comment]
It is easier than i suspected.
thanks a lot.

**Comment by kuno** [comment]
Sorry, but I re-installed all instance in a model, but still got a QuerySetError:

```
  QuerySetError: Field living_in is not an index. Cannot query.
```

**Comment by lsbardel** [comment]
If the field in question is a `CharField` change it to `SymbolField`. `CharField` is never an index, setting `index=True` to it does nothing.

**Comment by kuno** [comment]
Is SymbolField mutable?

**Comment by lsbardel** [comment]
Yes it is.
It should be used for (not too long) text fields which tend to repeat such as name of a person, name of groups, name of places and so forth.
Check https://github.com/lsbardel/python-stdnet/blob/0.7/examples/models.py
It should not be used for storing a web page for example. Use `CharField` for that.
SymbolField are by default `index`.
