### ISSUE TITLE
where is the data stored?

### ISSUE THREAD

**Issue by kuno** [lsbardel/python-stdnet#26]
I am relative new to reids (and stdnet), but I knew that redis's persistence system is based on snapshots and AOF. So according this basic understating, when I replaced the dump.rdb files with a new one, then restart redis-server, I should got a different database.

So it is surprise for me to found out that stdnet still show me the 'old' data after replaced the old dump.rdb. 
This just make think:  Maybe stdnet has its own persistence system other than dump.rdb?

**Comment by lsbardel** [comment]
No, data is stored in redis rdb file.

**Comment by kuno** [comment]
thanks for your rapid reply :)
