### ISSUE TITLE
ManyToManyField and get_or_create

### ISSUE THREAD

**Issue by christarnowski** [lsbardel/python-stdnet#3]
Let's say that we have the following in `models.py`:
    class Role(orm.StdModel):
        name = orm.SymbolField()

```
class Profile(orm.StdModel):
    roles = orm.ManyToManyField(model=Role, related_name="profiles")
```

Then the followng piece of code will fail:

```
role = models.Role.objects.get_or_create(name='admin')
profile.roles.add(role)
```

And the message will be:
    stdnet.exceptions.FieldValueError: (Role: Role object, False) is not an instance of models.role

UPDATE:
Obviously, the `get_or_create` method return a touple (obj, created). Everything is fine here - please close this issue.

**Comment by lsbardel** [comment]
Krzysztof,
The `get_or_create` method returns a `tuple` with two elements, the first element is the object and the second is a boolean (its value is `True` if the object was not available and therefore was created by the method).

Therefore:
    profile = Profile().save()
    role,created = Role.objects.get_or_create(name='admin')
    profile.roles.add(role)

will work

**Comment by christarnowski** [comment]
Yeah, I've noticed that one just after I've submitted the issue. Thanks!
