### ISSUE TITLE
Set pirmary key with name other than 'id' ?

### ISSUE THREAD

**Issue by kuno** [lsbardel/python-stdnet#30]
It is possible to set the primary key of a model with name other than 'id'? Every time I try to this, got an Exception:

```
 stdnet.exceptions.FieldError: Primary key must be named id
```

**Comment by lsbardel** [comment]
PK must be named `id`. Any reason you want to use a different name?

**Comment by kuno** [comment]
No, just my naive thought: if django orm can do this stdnet  may as well...
Any reason behind this design?

**Comment by lsbardel** [comment]
Simplicity.
To allow for a different name would be relatively easy, but I don't see any reason for it.
If you need other unique fields you can specify the `unique = True`  attribute in the Field constructor.
