### ISSUE TITLE
Zset field API

### ISSUE THREAD

**Issue by lsbardel** [lsbardel/python-stdnet#34]
Zset add new item by passing a score and a value. Zset fields should be able to bypass passing the score if a model is used as value.

**Comment by saidimu** [comment]
I haven't been able to find a `ZsetField` in `odm.structfields` (only the `Zset` structure exists in `odm.struct`).

Was this issue referring to `Zset` or `ZsetField` or both?

**Comment by lsbardel** [comment]
There is no `ZsetField` as such.
To have an ordered set as field (which is mapped to a zset in redis) use `odm.SetField(ordered=True)` in your model.
