### ISSUE TITLE
Add support for removing elements from ManyToMany relation

### ISSUE THREAD

**Issue by christarnowski** [lsbardel/python-stdnet#4]
There is no obvious way to remove an instance, or rather its reference, from `ManyToManyField` relation. Removing an instance using `QuerySet` deletes the relation AND the instance from database, so it can't be used here.

**Comment by lsbardel** [comment]
I added the `remove` method in `ManyToManyField` with tests:
    python runtests.py related

Fixed a bug too!
Code available in master.

**Comment by christarnowski** [comment]
Lovely, thanks!
