### ISSUE TITLE
Range filtering

### ISSUE THREAD

**Issue by lsbardel** [lsbardel/python-stdnet#41]
Indexing in `redis` backend is obtained via sets or sorted sets, depending on the meta ordering attribute.
These indices allow the filtering with respect specific index values. For example

```
MyModel.objects.filter(field1='bla', field2='foo')
```

But if we need to filter for a set of values we are stuck.

For example, lets consider an integer field, we would like to be able to do

```
MyModel.objects.filter(field3__ge=3)
```

To retrieve all instances with `field3` greater or equal 3.

This can be achieved in redis, by adding a sorted set for each indexed field.

**Comment by lsbardel** [comment]
The new implementation will allow range filters such as _greater-than_ 

```
*__gt
```

and _less-than_

```
*__lt
```

**Comment by saidimu** [comment]
Will this also include more Django-like filters such as `__*contains`, `__*startswith`, `__*endswidth` etc? https://docs.djangoproject.com/en/dev/ref/models/querysets/#field-lookups

These seem fairly simple to implement with redis' wildcard key patterns.

**Comment by lsbardel** [comment]
Possibly, but it is not as straightforward as it seems.
The `*__gt` and `*__lt` operators are relatively straightforward to implement as I will use redis sorted sets as indices.
I'm not sure what is the best way to implement the string filtering yet.

**Comment by lsbardel** [comment]
Main implementation done! More tests needed
