### ISSUE TITLE
Recover from data losing?

### ISSUE THREAD

**Issue by kuno** [lsbardel/python-stdnet#45]
For some strange reasons, I lost some data yesterday. 

Fortunately, I have some old redis dump files.
I has dumped the dump file into json format, and I saw some patterns in the names keys, such:
'stdnet.xxx.xxx:obj', 'stdnet.xxx.xxx:id', 'stdnet.xxx.xxx:idx'.

Can you explain these low level patters for me?
And I wandering Is there a way I can find back some lost data by merge the current dump file with old dump files?

thanks
--kuno

**Comment by kuno** [comment]
Also, I fount out that if one particular object was lost, the other objects that associated to it with a Foreignkey relationship will also lost silently.
Can I change this behavior?

**Comment by lsbardel** [comment]
Some information are provided here.

http://lsbardel.github.com/python-stdnet/backends/redis.html#redis-server

I'll try to improve the docs.
- The `basekey` for instances is built by concatenating `prefix` with `app_label` and `model_name`. The prefix is specified in the connection string:
  
    redis://localhost:8080?db=6&prefix=myprefix.
  
  by default it i set to `stdnet.`
- The `app_label` is set to the python module name holding the model. So if your model is in the `pippo.py` module, the `app_name` is `pippo`. You can override this behaviour by setting the `Meta.app_model` class in your model.
- The model name is the class name of your model (lower case).

http://lsbardel.github.com/python-stdnet/model/models.html#data-server-metaclass
