### ISSUE TITLE
object save to redis disk error

### ISSUE THREAD

**Issue by bsbrother** [lsbardel/python-stdnet#56]
stdnet is very well for me, but when i test to use it like:

class User(odm.StdModel):
    name = odm.SymbolField(unique = True)

odm.register(User, 'redis://127.0.0.1:6379?db=1') 
u1 = User(name='foo').save()

error :...
...python-stdnet/stdnet/lib/redis/client.py", line 1318, in parse_response
    raise RedisInvalidResponse("Wrong number of response items from "
stdnet.lib.redis.exceptions.RedisInvalidResponse: Wrong number of response items from pipeline execution

think you very much!

**Comment by lsbardel** [comment]
What stdnet and redis version are you using?

**Comment by bsbrother** [comment]
sorry, i use redis 2.4.12, I don't see overview then need redis >=2.6 .
think you comment! 
this soft is very good  again!
