### ISSUE TITLE
Running tests - not enough info in the documentation for me, help appreciated

### ISSUE THREAD

**Issue by tw-bert** [lsbardel/python-stdnet#59]
A warning up front: I'm not very experienced in python, so please forgive me if I ask something trivial.

I'm trying to follow the test instructions at http://lsbardel.github.io/python-stdnet/overview.html#running-tests .

I run Python 2.7.4 32-bit on windows (and 64-bit on IBM AIX and linux, but no stdnet there yet, first I'd like to do some tests).

I installed the following packages:
easy_install (by distribute_setup.py)
easy_install pip
Cython (win32 python 2.7 installer)
pip install mock
pip install coverage
pip install pulsar
pip install stdnet

The documentation refers to a "runtests.py", but that file is not installed by the pip stdnet install.
Then I downloaded a snapshot of the latest stdnet (just to try it) from github, grabbed runtests.py. Got a message:
Traceback (most recent call last):
  File "runtests.py", line 30, in <module>
    from stdnet.utils import test
ImportError: cannot import name test
So likewise, I put test.py from the snapshot in the site-packages/stdnet.

I issued the following command (note: my test redis server is on another machine, linux, and is up and running, and reachable from my windows machine):

D:\Program Files\Program_Progs\Python\2.7\Lib\site-packages\stdnet-tests>python runtests.py --server redis://srv-redis-dev-01:14111?db=12

Which gives me:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
Error occurred before starting tests
Traceback (most recent call last):
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\pulsar\apps\test__init__.py", line 267,
in monitor_start
    self.runner.on_start()
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\pulsar\apps\test\result.py", line 352, in _
    c = getattr(p, name)(*args)
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\stdnet\utils\test.py", line 179, in on_start
    raise pulsar.HaltServer('No server available. BAILING OUT')
HaltServer: No server available. BAILING OUT

Now I'm stuck. Any ideas? Did I miss something in the documentation?

Kind regards + TIA, tw

**Comment by lsbardel** [comment]
is that a semicolumn after redis?

redis;//srv-redis-dev-01:14111/?db=12

should be

redis://srv-redis-dev-01:14111?db=12

**Comment by tw-bert** [comment]
That was only a typo in the post, thanks for pointing that out. I'll edit that.
Response (bailing out) still the same...
I can run the examples by the way, stdnet seems to be configured okay. A simple test of pulsar (Hello world webserver) also works fine. I can't run runtests.py.

**Comment by lsbardel** [comment]
Can you run the tests with this flag `--log-level error` and check the output before `BAILING OUT` message?

**Comment by tw-bert** [comment]
First I got this message:

```
ImproperlyConfigured: Backend URI must not have a path. Found /
Error occurred before starting tests
```

I removed the trailing slash. _Edit: I see you already pointed this out before, "should be...", missed that initially_
Then I got this message:

```
2013-05-13 09:57:50 [p=5804,t=1724] [ERROR] [stdnet.test] Could not obtain server redis://srv-redis-dev-01:14111
Traceback (most recent call last):
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\stdnet\utils\test.py", line 170, in on_start
    s.ping()
AttributeError: 'BackendDataServer' object has no attribute 'ping'
```

To verify my redis server:

```
C:\Windows\system32>%AmberEclipseWorkspace%.metadata\.plugins\org.eclipse.debug.core\.launches\tools\Redis-Msdn-2.6_alpha_x64\redis-cli.exe -h srv-redis-dev-01 -p 14111
redis srv-redis-dev-01:14111> ping
PONG
```

**Comment by lsbardel** [comment]
OK,
to run tests you need to use the python-stdnet project directory. The best way to do that is to clone the repo

```
git://github.com/lsbardel/python-stdnet.git
```

move inside `python-stdnet` and issue `runtests.py`.

The test suite in `master branch` is not compatible with the `0.7` version.

Alternatively, if you want to run tests against the `0.7` version you need to download the tarball from https://pypi.python.org/pypi/python-stdnet and issue the same command from inside the python-stdnet directory. 

Tests and the test suite are not installed with `pip`, only the package is. This is a common pattern when packaging python libraries.

**Comment by tw-bert** [comment]
Ok, thanks a lot for your help, that clarifies things. I'll set this up later, might be one or two days. After that I'll close this issue.

Kind regards + amazing stuff btw (I was about to write something very similar when I stumbled upon stdnet), tw

**Comment by tw-bert** [comment]
Hi Luca, our system administrator Tjalling is picking up this issue.
He ran the tests on aix, and had some (probably minor) issues.

Just to let you know why I haven't closed this topic yet,

Kind regards, tw
