### ISSUE TITLE
Atomicity of stdnet transactions in relation to redis transactions

### ISSUE THREAD

**Issue by tw-bert** [lsbardel/python-stdnet#63]
Hi Luca,

As shown in a previous post, the commands between session.begin() and session.commit() aren't treated atomically.

If it fails midway, there are keys to be seen in the redis backend which haven't been backed out.

Redis' own transaction mechanism _is_ atomic. All in, or nothing in.
See: http://redis.io/topics/transactions 

Is it possible in stdnet to treat transactions atomically?

Kind regards, tw

**Comment by lsbardel** [comment]
Stdnet transactions are executed via a lua script

https://github.com/lsbardel/python-stdnet/blob/dev/stdnet/backends/redisb/lua/odm.lua
line 63-74

and therefore **they are atomic**, no other client is served while the lua script is executing.
The transaction starts when you invoke the `commit` method on a session.
Between `begin` and `commit` the database is not accessed at all.
You can `begin` a transaction and `commit` 1 hour later if you like.

A transaction always commits what it can. In your case `TestParent` was saved correctly, `TestChild` failed before it got sent to redis, it did not validate.

If an instance fails to commit in the server, the keys are rolled back for that instance only.

If you want to check that your models are correct before saving you can call the `is_valid` method on a model instance.

**Comment by tw-bert** [comment]
Hi Luca, that sounds great.

Now what do I have to do to roll back the complete transaction if  `is_valid` returns False?

Kind regards, tw

Edit:
To be clear, the code block where I started session:begin() exited with an exception. session:commit() was never called. add() statements were afterwards found in the redis backend.  `with` syntax could not be used because of program flow issues.

Edit2:
Ooops, error on my part. commit was called indeed. everything works exactly as it should. I'll quickly close this issue, sorry about this. Thank you for your help!
