### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by ghost** [lsbardel/python-stdnet#75]
from stdnet import odm

class Base(odm.StdModel):
    '''An abstract model. This won't have any data in the database.'''
    name = odm.SymbolField(unique = True)
    ccy  = odm.SymbolField()

```
def __unicode__(self):
    return self.name

class Meta:
    abstract = True
```

class Instrument(Base):
    itype = odm.SymbolField()

class Fund(Base):
    description = odm.CharField()

class PositionDescriptor(odm.StdModel):
    dt    = odm.DateField()
    size  = odm.FloatField()
    price = odm.FloatField()
    position = odm.ForeignKey("Position", index=False)

class Position(odm.StdModel):
    instrument = odm.ForeignKey(Instrument, related_name='positions')
    fund       = odm.ForeignKey(Fund)
    history    = odm.ListField(model=PositionDescriptor)

```
def __unicode__(self):
    return '%s: %s @ %s' % (self.fund,self.instrument,self.dt)
```

models = odm.Router('redis://localhost?db=1')
models.register(Instrument)
models.register(Fund)
models.register(PositionDescriptor,'redis://localhost?db=2')
models.register(Position,'redis://localhost?db=2')
f = models.fund.new(name="pluto", description="The pluto fund", ccy="EUR")

Your example doesn't work

i fixed a few typos, insead of orm it was odm
missed " next to pluto

**Comment by lsbardel** [comment]
You are missing the port:

```
models = odm.Router('redis://localhost:6379?db=1')
```

can you use the mail list for general questions? Issues are for bugs and feature requests.
Many thanks
