### ISSUE TITLE
Preferred way to do input validation?

### ISSUE THREAD

**Issue by SamuelMarks** [lsbardel/python-stdnet#76]
Given a simple example `class` like so:

```
from stdnet.odm import StdModel, SymbolField

class User(StdModel):
    email = SymbolField(primary_key=True)
```

E.g.: [SQLalchemy has a special syntax](http://docs.sqlalchemy.org/en/latest/orm/mapper_config.html#simple-validators):

```
from sqlalchemy.orm import validates

# Within the `class`/model
    @validates('email')
    def validate_email(self, key, address):
        assert '@' in address
        return address
```

What is the recommended way of performing validation, e.g.: to confirm that the input is a valid email-address?

Thanks for your input.

PS: Unrelated, but is there a way of attaching an expiry to a key in stdnet?

**Comment by lsbardel** [comment]
You need to write a custom `Field`, in your case

```
class EmailField(odm.SymbolField):

     def to_python(self, value, backend=None):
          value = super(EmailField, self).to_python(value, backend)
          assert '@' in value
          return value
```

Regarding expiries you can use the redis client.

Could you use the email list for general questions?
Github issues are for bugs and feature requests.
Many thanks

**Comment by SamuelMarks** [comment]
Thanks, will do in future; didn't know there was a mailing-list.
