### ISSUE TITLE
`primary_key` + `unique` are set; but the keys+values keep getting replaced?

### ISSUE THREAD

**Issue by AlecTaylor** [lsbardel/python-stdnet#77]
I have a fully self-contained [46 line example on the mailing-list](https://groups.google.com/d/topic/python-stdnet/yCgUtDL_cmA); except I've edited the register function with this to add it to a session for persisting to redis:

```
self.models_obj.session().add(
        self.models_obj.user.new(email=email, salt=salt,
                                 password=hashed_password))
```

When I run the script multiple times, I am left with just the two entries:

```
127.0.0.1:6379[3]> keys *
1) "__main__.user:id"
2) "__main__.user:obj:foo@bar.com"
```

Of which `hgetall __main__.user:obj:foo@bar.com` returns:

```
1) "password"
2) "c5ae488f79340d758d2d5cf11725a3cd347e03d5ba47e3f740506c505c6f625066a6f2b8ac470a8dad9b87706fbe0312de89a9c219ad9d43a1f5c9b268488d8d"
3) "salt"
4) "7363d66a7436478b87023412128000c3"
```

With both the `salt` and `password` being changed every-time I run [the script]((https://groups.google.com/d/topic/python-stdnet/yCgUtDL_cmA).

**Comment by lsbardel** [comment]
You have set `email` as the `primary_key`, therefore only one entry per email is allowed.
Unrelated to the issue, note that the `new` method in a manager already commit changes, there is no reason to use `new` and add the result to a session

```
u = user.new(email=email, salt=salt, password=hashed_password)
```

is enough to create the user.

**Comment by AlecTaylor** [comment]
Maybe it's expected behaviour; what I was expecting is an error, instead it silently replaces the `extra` field with the newest content I give it:

```
from stdnet.odm import SymbolField, CharField, StdModel, Router
from random import randint


class User(StdModel):
    email = SymbolField(primary_key=True, unique=True)
    extra = CharField()


if __name__ == '__main__':
    models = Router('redis://localhost:6379?db=3')
    models.register(User)
    models.user.new(email='foo@bar.com', extra=randint(1, 100))
```

So running the script a couple of times shouldn't give me different results like so:

```
127.0.0.1:6379[3]> hgetall __main__.user:obj:foo@bar.com
1) "extra"
2) "20"

127.0.0.1:6379[3]> hgetall __main__.user:obj:foo@bar.com
1) "extra"
2) "63"
```

In the user registration domain; I will have now have to do an explicit lookup to ensure that the given email address isn't already in the database! Isn't that what primary keys are for?!
